server:
  port: 8080
spring:
  redis:
    host: 139.196.161.252
    port: 6379
    password: xq85782621.
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 解决Date返回值的格式问题
  datasource:
    username: root
    password: Xq85782621.
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://139.196.161.252:3306/general?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC


mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.meizhi.model


